# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forn_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Administrator(object):
    def setupUi(self, Administrator):
        Administrator.setObjectName("Administrator")
        Administrator.resize(600, 600)
        Administrator.setMinimumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(Administrator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.PB_lk = QtWidgets.QPushButton(self.centralwidget)
        self.PB_lk.setObjectName("PB_lk")
        self.gridLayout.addWidget(self.PB_lk, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.LB_header = QtWidgets.QLabel(self.centralwidget)
        self.LB_header.setObjectName("LB_header")
        self.verticalLayout.addWidget(self.LB_header)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.img = QtWidgets.QGraphicsView(self.centralwidget)
        self.img.setMaximumSize(QtCore.QSize(240, 240))
        self.img.setObjectName("img")
        self.horizontalLayout.addWidget(self.img)
        self.LB_id = QtWidgets.QLabel(self.centralwidget)
        self.LB_id.setObjectName("LB_id")
        self.horizontalLayout.addWidget(self.LB_id)
        self.LB_username = QtWidgets.QLabel(self.centralwidget)
        self.LB_username.setObjectName("LB_username")
        self.horizontalLayout.addWidget(self.LB_username)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.PB_adm_akk = QtWidgets.QPushButton(self.centralwidget)
        self.PB_adm_akk.setObjectName("PB_adm_akk")
        self.gridLayout.addWidget(self.PB_adm_akk, 2, 0, 1, 1)
        self.PB_rate = QtWidgets.QPushButton(self.centralwidget)
        self.PB_rate.setObjectName("PB_rate")
        self.gridLayout.addWidget(self.PB_rate, 3, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 4, 0, 1, 1)
        Administrator.setCentralWidget(self.centralwidget)

        self.retranslateUi(Administrator)
        QtCore.QMetaObject.connectSlotsByName(Administrator)

    def retranslateUi(self, Administrator):
        _translate = QtCore.QCoreApplication.translate
        Administrator.setWindowTitle(_translate("Administrator", "Administrator"))
        self.PB_lk.setText(_translate("Administrator", "Личный кабинет"))
        self.LB_header.setText(_translate("Administrator", "АДМИНИСТРАТОР"))
        self.LB_id.setText(_translate("Administrator", "ID"))
        self.LB_username.setText(_translate("Administrator", "Username"))
        self.PB_adm_akk.setText(_translate("Administrator", "Администрирование аккаунтов региональных отделений"))
        self.PB_rate.setText(_translate("Administrator", "Рейтинг участников и итоги соревнований"))
        self.pushButton_4.setText(_translate("Administrator", "Аналитика"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Administrator = QtWidgets.QMainWindow()
    ui = Ui_Administrator()
    ui.setupUi(Administrator)
    Administrator.show()
    sys.exit(app.exec_())
