# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_partn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Part(object):
    def setupUi(self, Part):
        Part.setObjectName("Part")
        Part.resize(545, 669)
        Part.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_2 = QtWidgets.QGridLayout(Part)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.LB_username = QtWidgets.QLabel(Part)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LB_username.setFont(font)
        self.LB_username.setAlignment(QtCore.Qt.AlignCenter)
        self.LB_username.setObjectName("LB_username")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LB_username)
        self.PB_lk = QtWidgets.QPushButton(Part)
        self.PB_lk.setMinimumSize(QtCore.QSize(100, 75))
        self.PB_lk.setMaximumSize(QtCore.QSize(1000, 75))
        self.PB_lk.setSizeIncrement(QtCore.QSize(0, 0))
        self.PB_lk.setDefault(True)
        self.PB_lk.setObjectName("PB_lk")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.PB_lk)
        self.LB_header = QtWidgets.QLabel(Part)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.LB_header.setFont(font)
        self.LB_header.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.LB_header.setMouseTracking(True)
        self.LB_header.setAlignment(QtCore.Qt.AlignCenter)
        self.LB_header.setWordWrap(False)
        self.LB_header.setObjectName("LB_header")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LB_header)
        self.PB_appl = QtWidgets.QPushButton(Part)
        self.PB_appl.setMinimumSize(QtCore.QSize(100, 75))
        self.PB_appl.setMaximumSize(QtCore.QSize(1000, 75))
        self.PB_appl.setObjectName("PB_appl")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.PB_appl)
        self.PB_rate = QtWidgets.QPushButton(Part)
        self.PB_rate.setMinimumSize(QtCore.QSize(100, 75))
        self.PB_rate.setMaximumSize(QtCore.QSize(1000, 75))
        self.PB_rate.setObjectName("PB_rate")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.PB_rate)
        self.PB_result = QtWidgets.QPushButton(Part)
        self.PB_result.setMinimumSize(QtCore.QSize(100, 75))
        self.PB_result.setMaximumSize(QtCore.QSize(1000, 75))
        self.PB_result.setObjectName("PB_result")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.PB_result)
        self.img = QtWidgets.QGraphicsView(Part)
        self.img.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img.sizePolicy().hasHeightForWidth())
        self.img.setSizePolicy(sizePolicy)
        self.img.setMinimumSize(QtCore.QSize(240, 240))
        self.img.setMaximumSize(QtCore.QSize(240, 240))
        self.img.setBaseSize(QtCore.QSize(240, 240))
        self.img.setMouseTracking(False)
        self.img.setTabletTracking(False)
        self.img.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.img.setAutoFillBackground(False)
        self.img.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.img.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.img.setViewportUpdateMode(QtWidgets.QGraphicsView.MinimalViewportUpdate)
        self.img.setObjectName("img")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.img)
        self.gridLayout_2.addLayout(self.formLayout, 0, 1, 1, 1)

        self.retranslateUi(Part)
        QtCore.QMetaObject.connectSlotsByName(Part)

    def retranslateUi(self, Part):
        _translate = QtCore.QCoreApplication.translate
        Part.setWindowTitle(_translate("Part", "Part"))
        self.LB_username.setText(_translate("Part", "Имя пользователя"))
        self.PB_lk.setText(_translate("Part", "Личный Кабинет"))
        self.LB_header.setText(_translate("Part", "Партнер"))
        self.PB_appl.setText(_translate("Part", "Мои заявки"))
        self.PB_rate.setText(_translate("Part", "Рейтинг участников"))
        self.PB_result.setText(_translate("Part", "Итоги соревнований"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Part = QtWidgets.QDialog()
    ui = Ui_Part()
    ui.setupUi(Part)
    Part.show()
    sys.exit(app.exec_())
